;track ids
.ENUM
	track_brightman
	track_toadman
	track_ringman
	track_drillman
	track_pharaohman
	track_diveman
	track_skullman
	track_dustman
	track_cossack1_2
	track_wily1_2
	track_opening1
	track_ending
	track_boss_defeated
	track_password
	track_game_over
	track_boss_show
	track_stage_select
	track_boss_fighting
	track_title
	track_staff_roll
	track_get_weapon
	track_cossack3_4
	track_wily3_4
	track_flash_stopper
	track_rain_flush
	track_ring_boomerang
	track_drill_bomb
	track_pharaoh_shot
	track_lighting
	track_route
	track_jump_into_water
	track_1up
	track_charge_shot_full_charging_1
	track_mega_buster
	track_charge_shot_charging
	track_landing
	track_megaman_hit
	track_death
	track_enemy_hit
	track_charge_shot_full_charging_2
	track_explosion_1
	track_refill
	track_confirm
	track_enemy_immune
	track_door
	track_error
	track_select
	track_correct
	track_open_menu
	track_battan
	track_wire
	track_teleport_in
	track_34
	track_get_weapon_font
	track_warning
	track_explosion_2
	track_38
	track_appearing_block
	track_get_item
	track_wily_castle
	track_cossack_castle
	track_full_charge_shot
	track_pharaoh_full_charge_shot
	track_3f
	track_wily_ufo
	track_teleport_out
	track_42
	track_opening2
	track_nothing
	track_wily_fighting
	track_wily_defeated
.ENDENUM
