.SEGMENT "HOME"
.INCBIN  "home/home_0.bin"
.INCLUDE "home/sprites_bankswitch.asm"
.INCBIN  "home/home_1.bin"
;.INCLUDE "home/reset.asm"
;.INCLUDE "home/irq.asm"
;.INCLUDE "home/nmi.asm"
;.INCLUDE "home/vectors.asm"
