.SEGMENT "BANK30"
.INCLUDE "constants/tsa.asm"
.INCLUDE "screen/stage_select_capcom_logo_boss_show_weapon_license_scene_tsa.asm"
.INCLUDE "screen/stage_select_capcom_logo_boss_show_weapon_license_scene_mapset.asm"
.INCLUDE "screen/unused/unused_61110.asm"
.INCBIN  "gfx/48/48.chr"

.SEGMENT "BANK31"
.INCLUDE "screen/get_weapon_password_title_scene_tsa.asm"
.INCLUDE "screen/get_weapon_password_title_scene_mapset.asm"
.INCBIN  "gfx/49/49.chr"

.SEGMENT "BANK32"
.INCLUDE "screen/cossack_wily_castle_scene_tsa.asm"
.INCLUDE "screen/cossack_wily_castle_scene_mapset.asm"
.INCLUDE "screen/unused/unused_65110.asm"
.INCBIN  "gfx/50/50.chr"

.SEGMENT "BANK33"
.INCLUDE "screen/opening_scene_tsa.asm"
.INCLUDE "screen/opening_scene_mapset.asm"
.INCBIN  "gfx/51/51.chr"

.SEGMENT "BANK34"
.INCLUDE "screen/ending_scene_tsa.asm"
.INCLUDE "screen/ending_scene_mapset.asm"
.INCLUDE "screen/unused/unused_69110.asm"
