.SEGMENT "BANK0A"
.INCLUDE "constants/oam.asm"
.INCBIN  "sprites/sprites_10_0.bin"
.INCLUDE "sprites/oam_frameset_1.asm"
.INCBIN  "sprites/sprites_10_1.bin"
.INCBIN  "sprites/pointers/sprites_pointers_10.bin"
.INCLUDE "sprites/pointers/oam_frameset_pointers_1.asm"

.SEGMENT "BANK0C"
.INCBIN  "sprites/sprites_12_0.bin"
.INCLUDE "sprites/oam_frameset_2.asm"
.INCBIN  "sprites/sprites_12_1.bin"
.INCBIN  "sprites/pointers/sprites_pointers_12.bin"
.INCLUDE "sprites/pointers/oam_frameset_pointers_2.asm"

.SEGMENT "BANK0E"
.INCBIN  "sprites/sprites_14_0.bin"
.INCLUDE "sprites/oam_frameset_3.asm"
.INCBIN  "sprites/sprites_14_1.bin"
.INCBIN  "sprites/pointers/sprites_pointers_14.bin"
.INCLUDE "sprites/pointers/oam_frameset_pointers_3.asm"

.SEGMENT "BANK36"
.INCBIN  "sprites/sprites_54_0.bin"
.INCLUDE "sprites/oam_frameset_4.asm"
.INCBIN  "sprites/sprites_54_1.bin"
.INCBIN  "sprites/pointers/sprites_pointers_54.bin"
.INCLUDE "sprites/pointers/oam_frameset_pointers_4.asm"
