.SEGMENT "BANK0A"
.INCLUDE "constants/oam.asm"
.INCLUDE "sprites/oam_sprites_1.asm"
.INCBIN  "sprites/sprites_10.bin"
.INCLUDE "sprites/oam_frameset_1.asm"
.INCLUDE "sprites/unused/unused_1616b.asm"
.INCLUDE "sprites/pointers/oam_sprites_pointers_1.asm"
.INCBIN  "sprites/pointers/sprites_pointers_10.bin"
.INCLUDE "sprites/pointers/oam_frameset_pointers_1.asm"

.SEGMENT "BANK0C"
.INCLUDE "sprites/oam_sprites_2.asm"
.INCBIN  "sprites/sprites_12.bin"
.INCLUDE "sprites/oam_frameset_2.asm"
.INCLUDE "sprites/unused/unused_1aa7d.asm"
.INCLUDE "sprites/pointers/oam_sprites_pointers_2.asm"
.INCBIN  "sprites/pointers/sprites_pointers_12.bin"
.INCLUDE "sprites/pointers/oam_frameset_pointers_2.asm"

.SEGMENT "BANK0E"
.INCLUDE "sprites/oam_sprites_3.asm"
.INCBIN  "sprites/sprites_14.bin"
.INCLUDE "sprites/oam_frameset_3.asm"
.INCLUDE "sprites/unused/unused_1f807.asm"
.INCLUDE "sprites/pointers/oam_sprites_pointers_3.asm"
.INCBIN  "sprites/pointers/sprites_pointers_14.bin"
.INCLUDE "sprites/pointers/oam_frameset_pointers_3.asm"

.SEGMENT "BANK36"
.INCLUDE "sprites/oam_sprites_4.asm"
.INCBIN  "sprites/sprites_54.bin"
.INCLUDE "sprites/oam_frameset_4.asm"
.INCLUDE "sprites/unused/unused_6f4fa.asm"
.INCLUDE "sprites/pointers/oam_sprites_pointers_4.asm"
.INCBIN  "sprites/pointers/sprites_pointers_54.bin"
.INCLUDE "sprites/pointers/oam_frameset_pointers_4.asm"
