base $8000
;incsrc audio.asm
pad $8a40
incsrc track_data_pointers.asm
pad $8d09
;incsrc instruments.asm
;incsrc .\music\bright.asm
;incsrc .\music\toad.asm
;incsrc .\music\ring.asm
;incsrc .\music\drill.asm
;incsrc .\music\pharaoh.asm
;incsrc .\music\dive.asm
;incsrc .\music\skull.asm
;incsrc .\music\dust.asm
;incsrc .\music\cossack1.asm
;incsrc .\music\wily1.asm
;incsrc .\music\opening1.asm
;incsrc .\music\ending.asm
;incsrc .\music\stage_clear.asm
;incsrc .\music\pass_word.asm
;incsrc .\music\game_over.asm
;incsrc .\music\game_start.asm
;incsrc .\music\stage_select.asm
;incsrc .\music\boss.asm
;incsrc .\music\title.asm
;incsrc .\music\staff_roll.asm
;incsrc .\music\get_weapon.asm
;incsrc .\music\cossack3.asm
;incsrc .\music\wily3.asm
;incsrc .\sfx\flash_stopper.asm
;incsrc .\sfx\rain_flush.asm
;incsrc .\sfx\ring_boomerang.asm
;incsrc .\sfx\drill_bomb.asm
;incsrc .\sfx\uncharged_pharaoh_shot.asm
;incsrc .\sfx\lighting.asm
;incsrc .\sfx\routine_map.asm
;incsrc .\sfx\water.asm
;incsrc .\sfx\1up.asm
;incsrc .\unused\unused20.asm
;incsrc .\sfx\shoot.asm
;incsrc .\sfx\charging_buster.asm
;incsrc .\sfx\landing.asm
;incsrc .\sfx\damage_mm.asm
;incsrc .\sfx\death.asm
;incsrc .\sfx\destroy_enemy.asm
;incsrc .\sfx\fully_charging_buster.asm
;incsrc .\sfx\explosion.asm
;incsrc .\sfx\gain_bar.asm
;incsrc .\sfx\select_robot_master.asm
;incsrc .\sfx\shoot_recoil.asm
;incsrc .\sfx\boss_door.asm
;incsrc .\sfx\password_wrong.asm
;incsrc .\sfx\change_robot_master.asm
;incsrc .\sfx\password_correct.asm
;incsrc .\sfx\menu.asm
;incsrc .\sfx\battan.asm
;incsrc .\sfx\wire.asm
;incsrc .\sfx\teleport_in.asm
;incsrc .\unused\unused34.asm
;incsrc .\sfx\get_weapon_text.asm
;incsrc .\sfx\lab_alert.asm
;incsrc .\sfx\wily_castle_explosion.asm
;incsrc .\unused\unused38.asm
;incsrc .\sfx\yoku_block.asm
;incsrc .\music\get_items.asm
;incsrc .\music\wily_map.asm
;incsrc .\music\cossack_map.asm
;incsrc .\sfx\fully_charged_shoot.asm
;incsrc .\sfx\fully_pharaoh_shot.asm
;incsrc .\music\proto_whistle.asm
;incsrc .\sfx\ufo.asm
;incsrc .\sfx\teleport_out.asm
;incsrc .\music\opening2.asm
;incsrc .\music\last_boss.asm
;incsrc .\music\all_stage_clear.asm
;incsrc .\unused\unusedpre.asm
pad $e000