track_pointers:
	.DBYT music_brightman
	.DBYT music_toadman
	.DBYT music_ringman
	.DBYT music_drillman
	.DBYT music_pharaohman
	.DBYT music_diveman
	.DBYT music_skullman
	.DBYT music_dustman
	.DBYT music_cossack1_2
	.DBYT music_wily1_2
	.DBYT music_opening1
	.DBYT music_ending
	.DBYT music_boss_defeated
	.DBYT music_password
	.DBYT music_game_over
	.DBYT music_boss_show
	.DBYT music_stage_select
	.DBYT music_boss_fighting
	.DBYT music_title
	.DBYT music_staff_roll
	.DBYT music_get_weapon
	.DBYT music_cossack3_4
	.DBYT music_wily3_4
	.DBYT sfx_flash_stopper
	.DBYT sfx_rain_flush
	.DBYT sfx_ring_boomerang
	.DBYT sfx_drill_bomb
	.DBYT sfx_pharaoh_shot
	.DBYT sfx_lighting
	.DBYT sfx_route
	.DBYT sfx_jump_into_water
	.DBYT sfx_1up
	.DBYT sfx_charge_shot_full_charging_1
	.DBYT sfx_mega_buster
	.DBYT sfx_charge_shot_charging
	.DBYT sfx_landing
	.DBYT sfx_megaman_hit
	.DBYT sfx_death
	.DBYT sfx_enemy_hit
	.DBYT sfx_charge_shot_full_charging_2
	.DBYT sfx_explosion_1
	.DBYT sfx_refill
	.DBYT sfx_confirm
	.DBYT sfx_enemy_immune
	.DBYT sfx_door
	.DBYT sfx_error
	.DBYT sfx_select
	.DBYT sfx_correct
	.DBYT sfx_open_menu
	.DBYT sfx_battan
	.DBYT sfx_wire
	.DBYT sfx_teleport_in
	.DBYT sfx_34
	.DBYT sfx_get_weapon_font
	.DBYT sfx_warning
	.DBYT sfx_explosion_2
	.DBYT sfx_38
	.DBYT sfx_appearing_block
	.DBYT music_get_item
	.DBYT music_wily_castle
	.DBYT music_cossack_castle
	.DBYT sfx_full_charge_shot
	.DBYT sfx_pharaoh_full_charge_shot
	.DBYT music_3f
	.DBYT sfx_wily_ufo
	.DBYT sfx_teleport_out
	.DBYT sfx_42
	.DBYT music_opening2
	.DBYT 0
	.DBYT music_wily_fighting
	.DBYT music_wily_defeated
