;oamcoord pointers
;lo
	.LOBYTES oamcoord_300
	.LOBYTES oamcoord_301
	.LOBYTES oamcoord_302
	.LOBYTES oamcoord_303
	.LOBYTES oamcoord_304
	.LOBYTES oamcoord_305
	.LOBYTES oamcoord_306
	.LOBYTES oamcoord_307
	.LOBYTES oamcoord_308
	.LOBYTES oamcoord_309
	.LOBYTES oamcoord_30a
	.LOBYTES oamcoord_30b
	.LOBYTES oamcoord_30c
	.LOBYTES oamcoord_30d
	.LOBYTES oamcoord_30e
	.LOBYTES oamcoord_30f
	.LOBYTES oamcoord_310
	.LOBYTES oamcoord_311
	.LOBYTES oamcoord_312
	.LOBYTES oamcoord_313
	.LOBYTES oamcoord_314
	.LOBYTES oamcoord_315
	.LOBYTES oamcoord_316
	.LOBYTES oamcoord_317
	.LOBYTES oamcoord_318
	.LOBYTES oamcoord_319
	.LOBYTES oamcoord_31a
	.LOBYTES oamcoord_31b
	.LOBYTES oamcoord_31c
	.LOBYTES oamcoord_31d
	.LOBYTES oamcoord_31e
	.LOBYTES oamcoord_31f
	.LOBYTES oamcoord_320
	.LOBYTES oamcoord_321
	.LOBYTES oamcoord_322
	.LOBYTES oamcoord_323
	.LOBYTES oamcoord_324
	.LOBYTES oamcoord_325
	.LOBYTES oamcoord_326
	.LOBYTES oamcoord_327
	.LOBYTES oamcoord_328
	.LOBYTES oamcoord_329
	.LOBYTES oamcoord_32a
	.LOBYTES oamcoord_32b
	.LOBYTES oamcoord_32c
	.LOBYTES oamcoord_32d
	.LOBYTES oamcoord_32e
	.LOBYTES oamcoord_32f
	.LOBYTES oamcoord_330
	.LOBYTES oamcoord_331
	.LOBYTES oamcoord_332
	.LOBYTES oamcoord_333
	.LOBYTES oamcoord_334
	.LOBYTES oamcoord_335
	.LOBYTES oamcoord_336
	.LOBYTES oamcoord_337
	.LOBYTES oamcoord_338
	.LOBYTES oamcoord_339
	.LOBYTES oamcoord_33a
	.LOBYTES oamcoord_33b
	.LOBYTES oamcoord_33c
	.LOBYTES oamcoord_33d
	.LOBYTES oamcoord_33e
	.LOBYTES oamcoord_33f
	.LOBYTES oamcoord_340
	.LOBYTES oamcoord_341
	.LOBYTES oamcoord_342
	.LOBYTES oamcoord_343
	.LOBYTES oamcoord_344
	.LOBYTES oamcoord_345
	.LOBYTES oamcoord_346
	.LOBYTES oamcoord_347
	.LOBYTES oamcoord_348
	.LOBYTES oamcoord_349
	.LOBYTES oamcoord_34a
	.LOBYTES oamcoord_34b
	.LOBYTES oamcoord_34c
	.LOBYTES oamcoord_34d
	.LOBYTES oamcoord_34e
	.LOBYTES oamcoord_34f
	.LOBYTES oamcoord_350
	.LOBYTES oamcoord_351
	.LOBYTES oamcoord_352
	.LOBYTES oamcoord_353
	.LOBYTES oamcoord_354
	.LOBYTES oamcoord_355
	.LOBYTES oamcoord_356
	.LOBYTES oamcoord_357
	.LOBYTES oamcoord_358
	.LOBYTES oamcoord_359
	.LOBYTES oamcoord_35a
	.LOBYTES oamcoord_35b
	.LOBYTES oamcoord_35c
	.LOBYTES oamcoord_35d
	.LOBYTES oamcoord_35e
	.LOBYTES oamcoord_35f
	.LOBYTES oamcoord_360
	.LOBYTES oamcoord_361
	.LOBYTES oamcoord_362
	.LOBYTES oamcoord_363
	.LOBYTES oamcoord_364
	.LOBYTES oamcoord_365
	.LOBYTES oamcoord_366
	.LOBYTES oamcoord_367
	.LOBYTES oamcoord_368
	.LOBYTES oamcoord_369
	.LOBYTES oamcoord_36a
	.LOBYTES oamcoord_36b
	.LOBYTES oamcoord_36c
	.LOBYTES oamcoord_36d
	.LOBYTES oamcoord_36e
	.LOBYTES oamcoord_36f
	.LOBYTES oamcoord_370
	.LOBYTES oamcoord_371
	.LOBYTES oamcoord_372
	.LOBYTES oamcoord_373
	.LOBYTES oamcoord_374
	.LOBYTES oamcoord_375
	.LOBYTES oamcoord_376
	.LOBYTES oamcoord_377
	.LOBYTES oamcoord_378
	.LOBYTES oamcoord_379
	.LOBYTES oamcoord_37a
	.LOBYTES oamcoord_37b
	.LOBYTES oamcoord_37c
	.LOBYTES oamcoord_37d
	.LOBYTES oamcoord_37e
	.LOBYTES oamcoord_37f
	.LOBYTES oamcoord_380
	.LOBYTES oamcoord_381
	.LOBYTES oamcoord_382
	.LOBYTES oamcoord_383
	.LOBYTES oamcoord_384
	.LOBYTES oamcoord_385
	.LOBYTES oamcoord_386
	.LOBYTES oamcoord_387
	.LOBYTES oamcoord_388
	.LOBYTES oamcoord_389
	.LOBYTES oamcoord_38a
	.LOBYTES oamcoord_38b
	.LOBYTES oamcoord_38c
	.LOBYTES oamcoord_38d
	.LOBYTES oamcoord_38e
	.LOBYTES oamcoord_38f
	.LOBYTES oamcoord_390
	.LOBYTES oamcoord_391
	.LOBYTES oamcoord_392
	.LOBYTES oamcoord_393
	.LOBYTES oamcoord_394
	.LOBYTES oamcoord_395
	.LOBYTES oamcoord_396
	.LOBYTES oamcoord_397
	.LOBYTES oamcoord_398
	.LOBYTES oamcoord_399
	.LOBYTES oamcoord_39a
	.LOBYTES oamcoord_39b
	.LOBYTES oamcoord_39c
	.LOBYTES oamcoord_39d
	.LOBYTES oamcoord_39e
	.LOBYTES oamcoord_39f
	.LOBYTES oamcoord_3a0
	.LOBYTES oamcoord_3a1
	.LOBYTES oamcoord_3a2
	.LOBYTES oamcoord_3a3
	.LOBYTES oamcoord_3a4
	.LOBYTES oamcoord_3a5
	.LOBYTES oamcoord_3a6
	.LOBYTES oamcoord_3a7
	.LOBYTES oamcoord_3a8
	.LOBYTES oamcoord_3a9
	.LOBYTES oamcoord_3aa
	.LOBYTES oamcoord_3ab
	.LOBYTES oamcoord_3ac
	.LOBYTES oamcoord_3ad
	.LOBYTES oamcoord_3ae
	.LOBYTES oamcoord_3af
	.LOBYTES oamcoord_3b0
	.LOBYTES oamcoord_3b1
	.LOBYTES oamcoord_3b2
	.LOBYTES oamcoord_3b3
	.LOBYTES oamcoord_3b4
	.LOBYTES oamcoord_3b5
	.LOBYTES oamcoord_3b6
	.LOBYTES oamcoord_3b7
	.LOBYTES oamcoord_3b8
	.LOBYTES oamcoord_3b9
	.LOBYTES oamcoord_3ba
	.LOBYTES oamcoord_3bb
	.LOBYTES oamcoord_3bc
	.LOBYTES oamcoord_3bd
	.LOBYTES oamcoord_3be
	.LOBYTES oamcoord_3bf
	.LOBYTES oamcoord_3c0
	.LOBYTES oamcoord_3c1
	.LOBYTES oamcoord_3c2
	.LOBYTES oamcoord_3c3
	.LOBYTES oamcoord_3c4
	.LOBYTES oamcoord_3c5
	.LOBYTES oamcoord_3c6
	.LOBYTES oamcoord_3c7
	.LOBYTES oamcoord_3c8
	.LOBYTES oamcoord_3c9
	.LOBYTES oamcoord_3ca
	.LOBYTES oamcoord_3cb
	.LOBYTES oamcoord_3cc
	.LOBYTES oamcoord_3cd
	.LOBYTES oamcoord_3ce
	.LOBYTES oamcoord_3cf
	.LOBYTES oamcoord_3d0
	.LOBYTES oamcoord_3d1
	.LOBYTES oamcoord_3d2
	.LOBYTES oamcoord_3d3
	.LOBYTES oamcoord_3d4
	.LOBYTES oamcoord_3d5
	.LOBYTES oamcoord_3d6
	.LOBYTES oamcoord_3d7
	.LOBYTES oamcoord_3d8
	.LOBYTES oamcoord_3d9
	.LOBYTES oamcoord_3da
	.LOBYTES oamcoord_3db
	.LOBYTES oamcoord_3dc
	.LOBYTES oamcoord_3dd
	.LOBYTES oamcoord_3de
	.LOBYTES oamcoord_3df
	.LOBYTES oamcoord_3e0
	.LOBYTES oamcoord_3e1
	.LOBYTES oamcoord_3e2
	.LOBYTES oamcoord_3e3
	.LOBYTES oamcoord_3e4
	.LOBYTES oamcoord_3e5
	.LOBYTES oamcoord_3e6
	.LOBYTES oamcoord_3e7
	.LOBYTES oamcoord_3e8
	.LOBYTES oamcoord_3e9
	.LOBYTES oamcoord_3ea
	.LOBYTES oamcoord_3eb
	.LOBYTES oamcoord_3ec
	.LOBYTES oamcoord_3ed
	.LOBYTES oamcoord_3ee
	.LOBYTES oamcoord_3ef
	.LOBYTES oamcoord_3f0
	.LOBYTES oamcoord_3f1
	.LOBYTES oamcoord_3f2
	.LOBYTES oamcoord_3f3
	.LOBYTES oamcoord_3f4
	.LOBYTES oamcoord_3f5
	.LOBYTES oamcoord_3f6
	.LOBYTES oamcoord_3f7
	.LOBYTES oamcoord_3f8
	.LOBYTES oamcoord_3f9
	.LOBYTES oamcoord_3fa
	.LOBYTES oamcoord_3fb
	.LOBYTES oamcoord_3fc
	.LOBYTES oamcoord_3fd
	.LOBYTES oamcoord_3fe
	.LOBYTES oamcoord_3ff

;hi
	.HIBYTES oamcoord_300
	.HIBYTES oamcoord_301
	.HIBYTES oamcoord_302
	.HIBYTES oamcoord_303
	.HIBYTES oamcoord_304
	.HIBYTES oamcoord_305
	.HIBYTES oamcoord_306
	.HIBYTES oamcoord_307
	.HIBYTES oamcoord_308
	.HIBYTES oamcoord_309
	.HIBYTES oamcoord_30a
	.HIBYTES oamcoord_30b
	.HIBYTES oamcoord_30c
	.HIBYTES oamcoord_30d
	.HIBYTES oamcoord_30e
	.HIBYTES oamcoord_30f
	.HIBYTES oamcoord_310
	.HIBYTES oamcoord_311
	.HIBYTES oamcoord_312
	.HIBYTES oamcoord_313
	.HIBYTES oamcoord_314
	.HIBYTES oamcoord_315
	.HIBYTES oamcoord_316
	.HIBYTES oamcoord_317
	.HIBYTES oamcoord_318
	.HIBYTES oamcoord_319
	.HIBYTES oamcoord_31a
	.HIBYTES oamcoord_31b
	.HIBYTES oamcoord_31c
	.HIBYTES oamcoord_31d
	.HIBYTES oamcoord_31e
	.HIBYTES oamcoord_31f
	.HIBYTES oamcoord_320
	.HIBYTES oamcoord_321
	.HIBYTES oamcoord_322
	.HIBYTES oamcoord_323
	.HIBYTES oamcoord_324
	.HIBYTES oamcoord_325
	.HIBYTES oamcoord_326
	.HIBYTES oamcoord_327
	.HIBYTES oamcoord_328
	.HIBYTES oamcoord_329
	.HIBYTES oamcoord_32a
	.HIBYTES oamcoord_32b
	.HIBYTES oamcoord_32c
	.HIBYTES oamcoord_32d
	.HIBYTES oamcoord_32e
	.HIBYTES oamcoord_32f
	.HIBYTES oamcoord_330
	.HIBYTES oamcoord_331
	.HIBYTES oamcoord_332
	.HIBYTES oamcoord_333
	.HIBYTES oamcoord_334
	.HIBYTES oamcoord_335
	.HIBYTES oamcoord_336
	.HIBYTES oamcoord_337
	.HIBYTES oamcoord_338
	.HIBYTES oamcoord_339
	.HIBYTES oamcoord_33a
	.HIBYTES oamcoord_33b
	.HIBYTES oamcoord_33c
	.HIBYTES oamcoord_33d
	.HIBYTES oamcoord_33e
	.HIBYTES oamcoord_33f
	.HIBYTES oamcoord_340
	.HIBYTES oamcoord_341
	.HIBYTES oamcoord_342
	.HIBYTES oamcoord_343
	.HIBYTES oamcoord_344
	.HIBYTES oamcoord_345
	.HIBYTES oamcoord_346
	.HIBYTES oamcoord_347
	.HIBYTES oamcoord_348
	.HIBYTES oamcoord_349
	.HIBYTES oamcoord_34a
	.HIBYTES oamcoord_34b
	.HIBYTES oamcoord_34c
	.HIBYTES oamcoord_34d
	.HIBYTES oamcoord_34e
	.HIBYTES oamcoord_34f
	.HIBYTES oamcoord_350
	.HIBYTES oamcoord_351
	.HIBYTES oamcoord_352
	.HIBYTES oamcoord_353
	.HIBYTES oamcoord_354
	.HIBYTES oamcoord_355
	.HIBYTES oamcoord_356
	.HIBYTES oamcoord_357
	.HIBYTES oamcoord_358
	.HIBYTES oamcoord_359
	.HIBYTES oamcoord_35a
	.HIBYTES oamcoord_35b
	.HIBYTES oamcoord_35c
	.HIBYTES oamcoord_35d
	.HIBYTES oamcoord_35e
	.HIBYTES oamcoord_35f
	.HIBYTES oamcoord_360
	.HIBYTES oamcoord_361
	.HIBYTES oamcoord_362
	.HIBYTES oamcoord_363
	.HIBYTES oamcoord_364
	.HIBYTES oamcoord_365
	.HIBYTES oamcoord_366
	.HIBYTES oamcoord_367
	.HIBYTES oamcoord_368
	.HIBYTES oamcoord_369
	.HIBYTES oamcoord_36a
	.HIBYTES oamcoord_36b
	.HIBYTES oamcoord_36c
	.HIBYTES oamcoord_36d
	.HIBYTES oamcoord_36e
	.HIBYTES oamcoord_36f
	.HIBYTES oamcoord_370
	.HIBYTES oamcoord_371
	.HIBYTES oamcoord_372
	.HIBYTES oamcoord_373
	.HIBYTES oamcoord_374
	.HIBYTES oamcoord_375
	.HIBYTES oamcoord_376
	.HIBYTES oamcoord_377
	.HIBYTES oamcoord_378
	.HIBYTES oamcoord_379
	.HIBYTES oamcoord_37a
	.HIBYTES oamcoord_37b
	.HIBYTES oamcoord_37c
	.HIBYTES oamcoord_37d
	.HIBYTES oamcoord_37e
	.HIBYTES oamcoord_37f
	.HIBYTES oamcoord_380
	.HIBYTES oamcoord_381
	.HIBYTES oamcoord_382
	.HIBYTES oamcoord_383
	.HIBYTES oamcoord_384
	.HIBYTES oamcoord_385
	.HIBYTES oamcoord_386
	.HIBYTES oamcoord_387
	.HIBYTES oamcoord_388
	.HIBYTES oamcoord_389
	.HIBYTES oamcoord_38a
	.HIBYTES oamcoord_38b
	.HIBYTES oamcoord_38c
	.HIBYTES oamcoord_38d
	.HIBYTES oamcoord_38e
	.HIBYTES oamcoord_38f
	.HIBYTES oamcoord_390
	.HIBYTES oamcoord_391
	.HIBYTES oamcoord_392
	.HIBYTES oamcoord_393
	.HIBYTES oamcoord_394
	.HIBYTES oamcoord_395
	.HIBYTES oamcoord_396
	.HIBYTES oamcoord_397
	.HIBYTES oamcoord_398
	.HIBYTES oamcoord_399
	.HIBYTES oamcoord_39a
	.HIBYTES oamcoord_39b
	.HIBYTES oamcoord_39c
	.HIBYTES oamcoord_39d
	.HIBYTES oamcoord_39e
	.HIBYTES oamcoord_39f
	.HIBYTES oamcoord_3a0
	.HIBYTES oamcoord_3a1
	.HIBYTES oamcoord_3a2
	.HIBYTES oamcoord_3a3
	.HIBYTES oamcoord_3a4
	.HIBYTES oamcoord_3a5
	.HIBYTES oamcoord_3a6
	.HIBYTES oamcoord_3a7
	.HIBYTES oamcoord_3a8
	.HIBYTES oamcoord_3a9
	.HIBYTES oamcoord_3aa
	.HIBYTES oamcoord_3ab
	.HIBYTES oamcoord_3ac
	.HIBYTES oamcoord_3ad
	.HIBYTES oamcoord_3ae
	.HIBYTES oamcoord_3af
	.HIBYTES oamcoord_3b0
	.HIBYTES oamcoord_3b1
	.HIBYTES oamcoord_3b2
	.HIBYTES oamcoord_3b3
	.HIBYTES oamcoord_3b4
	.HIBYTES oamcoord_3b5
	.HIBYTES oamcoord_3b6
	.HIBYTES oamcoord_3b7
	.HIBYTES oamcoord_3b8
	.HIBYTES oamcoord_3b9
	.HIBYTES oamcoord_3ba
	.HIBYTES oamcoord_3bb
	.HIBYTES oamcoord_3bc
	.HIBYTES oamcoord_3bd
	.HIBYTES oamcoord_3be
	.HIBYTES oamcoord_3bf
	.HIBYTES oamcoord_3c0
	.HIBYTES oamcoord_3c1
	.HIBYTES oamcoord_3c2
	.HIBYTES oamcoord_3c3
	.HIBYTES oamcoord_3c4
	.HIBYTES oamcoord_3c5
	.HIBYTES oamcoord_3c6
	.HIBYTES oamcoord_3c7
	.HIBYTES oamcoord_3c8
	.HIBYTES oamcoord_3c9
	.HIBYTES oamcoord_3ca
	.HIBYTES oamcoord_3cb
	.HIBYTES oamcoord_3cc
	.HIBYTES oamcoord_3cd
	.HIBYTES oamcoord_3ce
	.HIBYTES oamcoord_3cf
	.HIBYTES oamcoord_3d0
	.HIBYTES oamcoord_3d1
	.HIBYTES oamcoord_3d2
	.HIBYTES oamcoord_3d3
	.HIBYTES oamcoord_3d4
	.HIBYTES oamcoord_3d5
	.HIBYTES oamcoord_3d6
	.HIBYTES oamcoord_3d7
	.HIBYTES oamcoord_3d8
	.HIBYTES oamcoord_3d9
	.HIBYTES oamcoord_3da
	.HIBYTES oamcoord_3db
	.HIBYTES oamcoord_3dc
	.HIBYTES oamcoord_3dd
	.HIBYTES oamcoord_3de
	.HIBYTES oamcoord_3df
	.HIBYTES oamcoord_3e0
	.HIBYTES oamcoord_3e1
	.HIBYTES oamcoord_3e2
	.HIBYTES oamcoord_3e3
	.HIBYTES oamcoord_3e4
	.HIBYTES oamcoord_3e5
	.HIBYTES oamcoord_3e6
	.HIBYTES oamcoord_3e7
	.HIBYTES oamcoord_3e8
	.HIBYTES oamcoord_3e9
	.HIBYTES oamcoord_3ea
	.HIBYTES oamcoord_3eb
	.HIBYTES oamcoord_3ec
	.HIBYTES oamcoord_3ed
	.HIBYTES oamcoord_3ee
	.HIBYTES oamcoord_3ef
	.HIBYTES oamcoord_3f0
	.HIBYTES oamcoord_3f1
	.HIBYTES oamcoord_3f2
	.HIBYTES oamcoord_3f3
	.HIBYTES oamcoord_3f4
	.HIBYTES oamcoord_3f5
	.HIBYTES oamcoord_3f6
	.HIBYTES oamcoord_3f7
	.HIBYTES oamcoord_3f8
	.HIBYTES oamcoord_3f9
	.HIBYTES oamcoord_3fa
	.HIBYTES oamcoord_3fb
	.HIBYTES oamcoord_3fc
	.HIBYTES oamcoord_3fd
	.HIBYTES oamcoord_3fe
	.HIBYTES oamcoord_3ff
